version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    pull-request-branch-name:
      prefix: "feature/dependabot"
      separator: "/"

  - package-ecosystem: "npm"
    directory: "/javascript"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    pull-request-branch-name:
      prefix: "feature/dependabot"
      separator: "/"

  - package-ecosystem: "bundler"
    directory: "/ruby"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    pull-request-branch-name:
      prefix: "feature/dependabot"
      separator: "/"
